### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by seductiveapps** [adrienverge/coucharchive#16]
root@crow:/home/rene/data1/htdocs/localhost/backupAndRestore# /root/.local/bin/coucharchive create --from https://admin:--blabla--@nicer.app:5984 --output "/home/rene/data1/htdocs/localhost/backups/20190916_115024/couchdb.backup.tar.gz"
CouchDB admin for https:: 

the .app TLD only allows https traffic by design.

so i need https support in coucharchive.. 
i hope this can be implemented without much time spent.

**Comment by big-r81** [comment]
Hi,

just skim through the source of coucharchive, maybe this line is your problem: https://github.com/adrienverge/coucharchive/blob/4928ff0da38c69f8c884bc8e4433330ff29e382a/coucharchive#L38

Cheers,
Ronny

**Comment by seductiveapps** [comment]
ok, i removed that condition from the code, ran the code, and it now outputs : 
 
/root/.local/bin/coucharchive create --from https://admin:texas.t33@nicer.app:5984 --output "/home/rene/data1/htdocs/localhost/backups/20190916_182517/couchdb.backup.tar.gz"Trying to increase the max number of open files (currently 1024)...
Traceback (most recent call last):
  File "/root/.local/bin/coucharchive", line 602, in <module>
    main()
  File "/root/.local/bin/coucharchive", line 585, in main
    create(args.source_server, args.output, ignore_dbs=ignore_dbs)
  File "/root/.local/bin/coucharchive", line 436, in create
    with CouchDBInstance(erlang_node) as local_couchdb:
  File "/root/.local/bin/coucharchive", line 87, in __init__
    self._setup()
  File "/root/.local/bin/coucharchive", line 148, in _setup
    shutil.copy('/etc/couchdb/' + file, self.confdir + '/' + file)
  File "/usr/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/couchdb/vm.args'

**Comment by big-r81** [comment]
The hint is in the last line:

```
FileNotFoundError: [Errno 2] No such file or directory: '/etc/couchdb/vm.args'
```
